# Generated by Django 5.2.8 on 2025-12-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'dept_tbl',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('work_part', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('A', '활성'), ('I', '비활성'), ('D', '삭제 예정')], default='A', max_length=1)),
                ('admin_yn', models.BooleanField()),
                ('delete_at', models.DateField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.dept')),
            ],
            options={
                'db_table': 'user_tbl',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['A', 'I', 'D'])), name='user_status_valid')],
            },
        ),
    ]
