# Generated by Django 5.2.7 on 2025-12-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', '활성'), ('I', '비활성'), ('D', '삭제 예정')], default='A', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['A', 'I', 'D'])), name='user_status_valid'),
        ),
    ]
