# Generated by Django 5.2.7 on 2025-12-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_calendar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                (
                    "state",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "oauth_state",
            },
        ),
    ]
