# Generated by Django 5.2.8 on 2025-12-11 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('s3_key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255)),
                ('delete_at', models.DateTimeField()),
            ],
            options={
                'db_table': 's3_file',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('transcript', models.TextField()),
                ('title', models.CharField(max_length=90)),
                ('meet_date_time', models.DateTimeField()),
                ('place', models.CharField(max_length=90)),
                ('summary', models.TextField(blank=True)),
                ('meeting_notes', models.TextField(blank=True)),
                ('domain_upload', models.BooleanField(default=False)),
                ('private_yn', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hosted_meetings', to='accounts.user')),
                ('record_url', models.ForeignKey(blank=True, db_column='record_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.s3file')),
            ],
            options={
                'db_table': 'meeting_tbl',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_content', models.CharField(max_length=90)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.user')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetings.meeting')),
            ],
            options={
                'db_table': 'task_tbl',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=16)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='meetings.meeting')),
            ],
            options={
                'db_table': 'domain_tbl',
                'unique_together': {('meeting', 'domain_name')},
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.user')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='meetings.meeting')),
            ],
            options={
                'db_table': 'attendee_tbl',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
