# Generated by Django 5.2.8 on 2025-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='private_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='domain',
            table='domain_tbl',
        ),
    ]
