# Generated by Django 5.2.8 on 2025-12-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
