# Generated by Django 5.2.8 on 2025-12-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_task_task_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='domain_upload',
        ),
        migrations.AddField(
            model_name='meeting',
            name='domain',
            field=models.BooleanField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
