# Generated by Django 5.2.8 on 2025-12-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0003_remove_meeting_domain_upload_meeting_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="domain",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
