# Generated by Django 5.2.7 on 2025-12-16 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_account_lock_fields'),
        ('meetings', '0004_alter_meeting_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hosted_meetings', to='accounts.user'),
        ),
    ]
