# Generated by Django 5.2.8 on 2025-12-17 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3file',
            name='record_url',
            field=models.URLField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='record_url',
            field=models.ForeignKey(blank=True, db_column='record_url', null=True, on_delete=django.db.models.deletion.SET_NULL, to='meetings.s3file', to_field='record_url'),
        ),
    ]
