# Generated by Django 5.2.8 on 2025-12-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_s3file_record_url_alter_meeting_record_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s3file',
            name='record_url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
